- hosts: localhost
  become: true
  module_defaults:
    apt:
      force_apt_get: yes
  vars:
    ansible_user: mike
    containerd_version: 1.5.10-1
    docker_compose_version: v2.3.3
    docker_version: 20.10.6~3-0
    docker_download: 'https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64'
    hugo_version: 0.94.2
    jb_sha256: 3b2cfc340d9116699d9e83173ea79d325df7f940d6f446d34076833608a99139
    jb_version: 1.22.10970
    node_version: 14.x
    smartgit_version: "21_2_2"
    tf_version: 1.1.7
  tasks:
    - name: 'Configure bash profile'
      copy:
        src: files/.profile
        dest: /home/{{ ansible_user }}/.profile
        owner: "{{ ansible_user }}" 

    - name: 'Configure bash aliases'
      copy:
        src: files/.bash_aliases
        dest: /home/{{ ansible_user }}/.bash_aliases
        owner: "{{ ansible_user }}" 

    - name: 'Install packages'
      apt:
        pkg:
          - htop
          - unzip
          - git
          - solaar
          - gnome-tweak-tool
          - curl
          - tree
          - python3-pip
          - gnome-sushi

    - name: Ensure botocore, boto3, and psutil modules are installed
      pip:
        name: [ "boto3", "botocore", "psutil"]
        extra_args:  "--user"

    - name: Telegram
      snap:
        name: telegram-desktop
        channel: latest/stable
    - name: 'AWS CLI'
      include: aws-cli.yml
    - name: 'JetBrains'
      include: jetbrains.yml
    - name: 'Programming Languages'
      include: languages.yml
    - name: 'Sublime'
      include: sublime.yml
    - name: 'syntevo Tools - SmartGit'
      include: syntevo.yml
    - name: 'Terraform'
      include: terraform.yml
    - name: 'Docker'
      include: docker.yml
