- hosts: localhost
  become: true
  module_defaults:
    apt:
      force_apt_get: yes
  vars:
    tf_version: 0.12.29
    tf_sha256: 872245d9c6302b24dc0d98a1e010aef1e4ef60865a2d1f60102c8ad03e9d5a1d
    jb_version: 1.18.7455
    jb_sha256: 5d8acef010816cec5082e37cf07607c59cf1534d3fd7d9546d5cbb55149cdd54
    dropbox_version: 2019.02.14
    node_version: 12.x
    smartgit_version: "20_1_5"
    smartsync_version: "4_1_1_1"
    hugo_version: 0.74.3
    docker_download: 'https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64'
    containerd_version: 1.3.7-1
    docker_version: 19.03.13~3-0
    machine_version: v0.16.2
    ansible_user: mike
  tasks:
    - name: 'Configure tmux'
      copy:
        src: files/.tmux.conf
        dest: /home/{{ ansible_user }}/.tmux.conf
        owner: "{{ ansible_user }}" 

    - name: 'Configure bash profile'
      copy:
        src: files/.profile
        dest: /home/{{ ansible_user }}/.profile
        owner: "{{ ansible_user }}" 

    - name: 'Configure bash aliases'
      copy:
        src: files/.bash_aliases
        dest: /home/{{ ansible_user }}/.bash_aliases
        owner: "{{ ansible_user }}" 

    - name: 'Install packages'
      apt:
        pkg:
          - htop
          - unzip
          - git
          - solaar
          - gnome-tweak-tool
          - tmux
          - curl
          - tree
          - python3-pip

    - name: Ensure botocore, boto3, and psutil modules are installed
      pip:
        name: [ "boto3", "botocore", "psutil"]
        extra_args:  "--user"

    - name: Telegram
      snap:
        name: telegram-desktop
        channel: latest/stable
    - name: 'AWS CLI'
      include: aws-cli.yml
    - name: 'JetBrains'
      include: jetbrains.yml
    - name: 'Programming Languages'
      include: languages.yml
    - name: 'Sublime'
      include: sublime.yml
    - name: 'syntevo Tools - SmartGit and SmartSynchronize'
      include: syntevo.yml
    - name: 'Gnome Terminal'
      include: terminal.yml
    - name: 'Terraform'
      include: terraform.yml
    - name: 'Zoom conferencing'
      include: zoom.yml
    - name: 'Docker'
      include: docker.yml

# TODO SDKMAN!
# TODO Gradle
# TODO Groovy
