- hosts: localhost
  become: true
  module_defaults:
    apt:
      force_apt_get: yes
  vars:
    tf_version: 0.12.21
    tf_sha256: ca0d0796c79d14ee73a3d45649dab5e531f0768ee98da71b31e423e3278e9aa9
    jb_version: 1.16.6319
    jb_sha256: 4e6f333839af8330a09d9d6fdcd6a635c9ca1f0ae239d8f268249dbd095ca880
    dropbox_version: 2019.02.14
    node_version: 10.x
    smartgit_version: "19_1_6"
    smartsync_version: "4_0_3"
    ansible_user: mike
  tasks:
    - name: 'Configure bash'
      copy:
        src: files/.profile
        dest: /home/{{ ansible_user }}/.profile

    # - name: 'Install packages'
    #   apt:
    #     pkg:
    #       - htop
    #       - unzip
    #       - git
    #       - solaar
    #       - python-pip
    #       - gnome-tweak-tool
    #       - tmux

    # - name: Ensure botocore, boto3, and psutil modules are installed
    #   pip:
    #     name: [ "boto3", "botocore", "psutil"]
    #     extra_args:  "--user"

    # - name: 'AWS CLI'
    #   include: aws-cli.yml
    # - name: 'JetBrains'
    #   include: jetbrains.yml
    # - name: 'Programming Languages'
    #   include: languages.yml
    # - name: 'Sublime'
    #   include: sublime.yml
    # - name: 'syntevo Tools - SmartGit and SmartSynchronize'
    #   include: syntevo.yml
    # - name: 'Gnome Terminal'
    #   include: terminal.yml
    # - name: 'Terraform'
    #   include: terraform.yml
    - name: 'Zoom conferencing'
      include: zoom.yml

# TODO SDKMAN!
# TODO Gradle
# TODO Groovy
