- hosts: localhost
  become: true
  module_defaults:
    apt:
      force_apt_get: yes
  vars:
    tf_version: 0.12.21
    tf_sha256: ca0d0796c79d14ee73a3d45649dab5e531f0768ee98da71b31e423e3278e9aa9
    jb_version: 1.16.6319
    jb_sha256: 4e6f333839af8330a09d9d6fdcd6a635c9ca1f0ae239d8f268249dbd095ca880
    dropbox_version: 2019.02.14
    node_version: 10.x
    smartgit_version: "19_1_6"
    smartsync_version: "4_0_3"
  tasks:
    - name: 'Install packages'
      apt:
        pkg:
          - htop
          - unzip
          - git
          - solaar
          - python-pip
    - name: Ensure botocore and boto3 modules are installed
      pip:
        name: [ "boto3", "botocore"]
        extra_args:  "--user"
    - name: 'SSM Test'
      debug: 
          msg: "{{ lookup('aws_ssm', '/mike/mxl-client/user-pool-client-id', region='us-east-1' ) }}"
      become: yes
      become_method: su
      become_user: mike

    - name: Go
      snap:
        name: go
        classic: yes
        channel: latest/stable

    - name: 'Download Terraform {{ tf_version }}'
      get_url:
        url: https://releases.hashicorp.com/terraform/{{ tf_version }}/terraform_{{ tf_version }}_linux_amd64.zip
        dest: /tmp/terraform_{{ tf_version }}_linux_amd64.zip
        checksum: sha256:'{{ tf_sha256 }}'
    - name: 'Extract Terraform {{ tf_version }}'
      unarchive:
        src: /tmp/terraform_{{ tf_version }}_linux_amd64.zip
        dest: /usr/local/bin

    - name: 'Download JetBrains Toolbox {{ jb_version }}'
      get_url:
        url: https://download.jetbrains.com/toolbox/jetbrains-toolbox-{{ jb_version }}.tar.gz
        dest: /tmp/jetbrains-toolbox-{{ jb_version }}.tar.gz
        checksum: sha256:'{{ jb_sha256 }}'
    - name: 'Extract JetBrains Toolbox {{ jb_version }}'
      unarchive:
        src: /tmp/jetbrains-toolbox-{{ jb_version }}.tar.gz
        dest: /tmp
    - name: 'Install JetBrains Toolbox {{ jb_version }}'
      command:
        cmd: /tmp/jetbrains-toolbox-{{ jb_version }}/jetbrains-toolbox
        creates: ~/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox

    - name: 'Install Dropbox'
      apt:
        deb: https://linux.dropbox.com/packages/ubuntu/dropbox_{{ dropbox_version }}_amd64.deb

    - name: 'Add NodeSource Key'
      apt_key: 
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    - name: 'Add NodeSource Repository'
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node_{{ node_version }} {{ ansible_distribution_release }} main' 
        update_cache: yes
    - name: 'Install NodeJS'
      apt:
        name: nodejs

    - name: 'Install Smart Git {{ smartgit_version }}'
      apt:
        deb: 'https://www.syntevo.com/downloads/smartgit/smartgit-{{smartgit_version}}.deb'
    - name: 'Install Smart Sync {{ smartsync_version }}'
      apt:
        deb: 'https://www.syntevo.com/downloads/smartsynchronize/smartsynchronize-{{smartsync_version}}.deb'

    - name: 'Add Sublime Key'
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
    - name: 'Add Sublime Repository'
      apt_repository:
        repo: deb https://download.sublimetext.com/ apt/stable/
        update_cache: yes
    - name: 'Install Sublime 3'
      apt:
        name: sublime-text

    - name: 'Download AWS CLI Bundle'
      get_url: 
        url: https://s3.amazonaws.com/aws-cli/awscli-bundle.zip
        dest: /tmp/awscli-bundle.zip
    - name: 'Extract AWS CLI Bundle'
      unarchive:
        src: /tmp/awscli-bundle.zip
        dest: /tmp
    - name: 'Install AWS CLI'
      command:
        cmd: /tmp/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
# TODO Mysql
# TODO Sublime Key Bindings
# TODO Sublime Packages
# TODO SDKMAN!
# TODO Gradle
# TODO Groovy
# TODO JDK 11
