- hosts: localhost
  become: true
  module_defaults:
    apt:
      force_apt_get: yes
  vars:
    tf_version: 0.12.24
    tf_sha256: 602d2529aafdaa0f605c06adb7c72cfb585d8aa19b3f4d8d189b42589e27bf11
    jb_version: 1.17.7018
    jb_sha256: 55d1598083a60fb4d2855a764e136b7fa760fb5b8626ad79ac6f4925909e5878
    dropbox_version: 2019.02.14
    node_version: 12.x
    smartgit_version: "19_1_6"
    smartsync_version: "4_0_3"
    hugo_version: 0.68.3
    docker_download: 'https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64'
    containerd_version: 1.2.13-1
    docker_version: 19.03.8~3-0~ubuntu-bionic_amd64
    machine_version: v0.16.2
    ansible_user: mike
  tasks:
    - name: 'Configure bash profile'
      copy:
        src: files/.profile
        dest: /home/{{ ansible_user }}/.profile
        owner: "{{ ansible_user }}" 

    - name: 'Configure bash aliases'
      copy:
        src: files/.bash_aliases
        dest: /home/{{ ansible_user }}/.bash_aliases
        owner: "{{ ansible_user }}" 

    - name: 'Install packages'
      apt:
        pkg:
          - htop
          - unzip
          - git
          - git-lfs
          - solaar
          - python-pip
          - gnome-tweak-tool
          - tmux
          - curl
          - tree

    - name: Ensure botocore, boto3, and psutil modules are installed
      pip:
        name: [ "boto3", "botocore", "psutil"]
        extra_args:  "--user"

    - name: Telegram
      snap:
        name: telegram-desktop
        channel: latest/stable

    - name: Inkscape
      snap:
        name: inkscape
        channel: latest/stable

    - name: Asciinema
      snap:
        name: asciinema
        channel: latest/stable
        classic: yes
        
    - name: 'AWS CLI'
      include: aws-cli.yml
    - name: 'JetBrains'
      include: jetbrains.yml
    - name: 'Programming Languages'
      include: languages.yml
    - name: 'Sublime'
      include: sublime.yml
    - name: 'syntevo Tools - SmartGit and SmartSynchronize'
      include: syntevo.yml
    - name: 'Gnome Terminal'
      include: terminal.yml
    - name: 'Terraform'
      include: terraform.yml
    - name: 'Zoom conferencing'
      include: zoom.yml
    - name: 'Docker'
      include: docker.yml

# TODO SDKMAN!
# TODO Gradle
# TODO Groovy
